### ISSUE TITLE
Event report tables are not displayed in dashboards

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#128]
See Inpatient discharge dashbaord

2.29 shows blank screen and "Bad server response" message 
2.28 blamk screen and no message
2.27 works well

**Comment by idelcano** [comment]
The report tables work ok, but the servers has some problems with the permissions.

 F example 2.28 works with the user admin, but doesn't work with android. And 2.29 works with the system user, but doesn't work with admin(sierra leona is not assigned to that user) or android.
