### ISSUE TITLE
Date restrictions on Category Options are applied with incorrect start date in Android DC

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#13]
If start-and-end-date restrictions are applied to a Category Option, they are generally honoured in Android Data Capture. However, the dates are slightly wrong - the option is in fact missing from the first period where it should be available (it appears in all subsequent periods).
For example, if the Category Option 'African Medical and Research Foundation' has a date restriction imposed of 1 Jan 2016 to 31 Jan 2017, then in the Data Set 'ART monthly summary', the option should be available for the periods January 2016 to January 2017, and not available from February 2017 onwards. This works correctly on web Data Entry (screenshot attached), however in Android Data Capture, this option is in fact only available from February 2016, ie it skips the first period it should be available (January 2017). (The open drop-down unfortunately disappeared when I shook the device, so is not visible in the screenshot.)
It seems to be the first period that is consistently omitted - so if only one period is covered (eg dates are set as 1 Jan 2017 to 31 Jan 2017), then the option will never be available.
Note that an org unit restrictions was applied to a different Category/different Option within the same CatCombo, and it appears to work correctly on Android Data Capture.
[Note: due to a current bug, you will need to delete compulsory data elements from the 'ART monthly summary' Data Set in order for it to load into Android DC.]

**Comment by ifoche** [comment]
![periods.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46f891882a8d87bacda5fd53b652fa912a5265296b51fa7b2687b17de9152c54585a1cac415a5f16afabdb2aa6a42062c80d55b98e30063e937f03a6aa8019b500be298c4783bebc8b44c1e13c37aa.jpg)

![periods_web.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46f891882a8d87bab0feba41e611b2843b492d762a10e17132d0ba78e9402954595849a9465d0d44fcfb8979f5e46e718a4e17ff933c0120996048e6edc00db513b826814e81bfbb824ac8e83e22e18f8c5d73.png)

**Comment by idelcano** [comment]
@ifoche  this is  datacapture bug. i will move it
