### ISSUE TITLE
Pivot tables values not shown (all but one)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#133]
Data not shown:
Delivery: Live births in facilities last 4 quarters (delivery)
Immunization: Indicators last 12 months with legend set (Immunization)
Immunization: Data by facility type last 4 quarters (Immunization data)
Immunization: Data by districts last 4 quarters (Immunization data)

Data Shown: DS: Cases by Diagnosis last year (Disease Surveillance)

Behaviour affecting in 2.28 only

This issue is very likely to be another representation of the same problem seen in #132. Please just verify that it is what the server is sending, and add a comment with the confirmation.

**Comment by idelcano** [comment]
It is a server problem. the user doesn't have permissions.. 
When you open: 
Delivery: Live births in facilities last 4 quarters (delivery)
The server shows:
User is not allowed to view org unit: O6uvpzGd6pu

When you open: 
Immunization: Indicators last 12 months with legend set (Immunization)
Immunization: Data by facility type last 4 quarters (Immunization data)
Immunization: Data by districts last 4 quarters (Immunization data)
The server shows:
User is not allowed to view org unit: JNb63DIHuwU
