### ISSUE TITLE
Changes in charts in web are not reflected in the android app

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#134]
Alpha testers report:

2.27 for: ANC: ANC IPT 1 Coverage last 12 months districts in Antenatal Care Dashboard
- Change org units selection was reflected after two syncs.
- Change in chart type is working properly.

2.28 (server used: /2.28)
- Not able to test, charts are not showing even after several log in and synchronizations.

2.29
- charts are not showing even after several log in and synchronizations.The only charts able to see are: ANC: 4+ visits by Facility type last year and ANC: Fixed vs Outreach last year

NOTE: we are using Samsung Note 4 v6.0.1 and Samsung Note 8 v8.0.0

**Comment by manuelplazaspalacio** [comment]
2.28 and 2.29 we see the same in the web.
For 2.27 if you wait for the refresh to end it works correctly.
