### ISSUE TITLE
Reporting rates: HIV, PMTCT, TB Trends chart (and other similar) doesn't show, while other charts show

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#39]
Looks like the API is working for some URLs but not for other ones. Review if we can get it working with css+html or with png, or with api/25

**Comment by xurxodev** [comment]
Server response wrong images, I have created an issue in JIRA
https://jira.dhis2.org/browse/DHIS2-1922
