### ISSUE TITLE
Study each API call load with ab/JMeter

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#71]
Modify wiki pages including that information

**Comment by tokland** [comment]
Results for concurrency=1 and concurrency=10 for server https://play.dhis2.org/android-previous1 and connections from the same machine:

https://github.com/EyeSeeTea/ESTools/tree/feature/dhis2-benchmarking/DHIS2/benchmarking/results

**Comment by ifoche** [comment]
Thanks @tokland. Which tool did you finally use to generate these results?

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/ESTools/blob/feature/dhis2-benchmarking/DHIS2/benchmarking/run-benchmarks.py

Using a YAML configuration file + `ab`, which is the most simple CLI tool for individual calls.

**Comment by ifoche** [comment]
I see...looks very good. And I suppose that values are in milliseconds and represent the latency, right? 

I'm reading a little bit more about ab vs JMeter, and seems like most of people says that ab is a good tool for very basic analysis, but if you want to do get more details JMeter is more appropriate. You have plugins like [this one](https://jmeter-plugins.org/wiki/PerfMon/) that offers even memory and cpu usage server side, and can also be used from command-line. I guess you already spent some time using ab, but...did you give a try to JMeter too?

**Comment by tokland** [comment]
Yes the, first field is "secs/req (mean)" (there was a header but I removed it to make sorting easier). That's what I've also seen, `ab` works well with single URLs; to test a real multi-step scenario something like `jmeter` is required. I am currently setting it up to record actions through a proxy, I think introducing the data manually will take a lot of time and won't be precise.
