### ISSUE TITLE
Create a common user profile

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#72]
Describe the typical user workflow in terms of server load

**Comment by ifoche** [comment]
2 main situations:
- [x] Initial sync
- [x] Normal operation

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/ESTools/wiki/Dhis2-Benchmarking#dhis2androiddashboard

Sorry for the delay, it's been quite a work to setup the full system, configure jmeter and generate the graphs.

**Comment by ifoche** [comment]
@tokland results are exactly what we were looking for. Only a couple of questions:
-  Looks like memory usage is always using the maximum available (3.2GB apparently). Have you seen other values in memory chart so you can confirm that is not a measurement failure?
- Re the failing queries even in an optimal situation, could you provide which queries are so we can study if it is simply an ID failure or if there's something to investigate there in the app sync?
- [This is](https://github.com/EyeSeeTea/ESTools/tree/feature/dhis2-benchmarking/DHIS2/benchmarking/jmeter/dhis2-android-dashboard) the raw data for the tests, right?
- If I'm properly interpreting the results, from 25 users on some little problems could arise, with an incremental delay in sync, but users would be able to use without problems dashboard app until we reach the 40 users concurrent limit. Do you think that's correct?

Apart from that, I think you can go on and launch the measures for the rest of the apps

Thank you very much!

**Comment by tokland** [comment]
- Memory: I've checked the other graphs for tests with less users, and in fact RAM usage is increasing, users=1 starts with 1.4G and users=35 ends up with 3.2G. Check the perfmon images.
- Failing queries: 26 requests from the JTL file: `$ cat jmeter/dhis2-android-dashboard/android-current-users1.jtl  | awk -F',' '$8 == "false"'`. This is the typical example of a failed request, images: `https://play.dhis2.org/android-current/api/maps/mZKtu7sY0w4/data.png` -> 500 ""Width (365) and height (0) cannot be <= 0".
- raw data: yes, this directory contains the results. JTL are CSV files with the JMeter output, I use them to draw the graphs.
- The server can manage up to 40 users with a good success rate for dashboards, indeed, but the response times are not really great for > 10 users. For example, 25 simultaneous users have an initial sync is ~ 650secs ~ 10minutes (mean time per user). A more reasonable upper limit for usable interaction maybe should be lower, 10-15 users, but of course that's subjective. Note that those are _completely_ simultaneous users, in a real scenario you probably can handle more "real" users (which do not perfectly synchronize and make pauses between actions).

**Comment by ifoche** [comment]
I forgot to say it here but, thank you @tokland
