### ISSUE TITLE
Find the system limits

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-dashboard#73]
Recommendations in terms of memory & minimum Amazon instance required

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/ESTools/wiki/Dhis2-Benchmarking#dhis2androiddashboard

**Comment by tokland** [comment]
I've added a wiki page as a preliminary analysis of the hangs:

https://github.com/EyeSeeTea/ESTools/wiki/DHIS2-server-hangs-on-heavy-concurrent-requests
